[workspace]
authors = ["Ben Woodcroft <benjwoodcroft@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "sracat-rs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build --release"
sracat-rs = "cargo run --release --"

[dependencies]
ncbi-vdb = "==3.4.1"
c-compiler = ">=1.11.0,<2"
zlib = ">=1.3.2,<2"
sra-tools = ">=3.4.1,<4"
rust = ">=1.96.0,<1.97"

[feature.dev.dependencies]
snakemake = ">=9.23.1,<10"

[feature.dev.tasks]
fetch-testdata = "snakemake --cores 1"
test = { cmd = "cargo test", depends-on = ["fetch-testdata"] }

[environments]
dev = ["dev"]
